apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: '1'
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: MySQL
      type: mysql
      access: proxy
      orgId: 1
      url: <endpoint>:3306
      password: <RDS MySQL Password>
      user: <RDS MySQL User>
      database: <RDS MySQL Database Name>
      # allow users to edit datasources from the UI.
      editable: false
    - name: OpenFaaS
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus.openfaas.svc.cluster.local:9090
      # allow users to edit datasources from the UI.
      editable: true
