{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "words-counter.serviceAccountName" . }}
  labels:
{{ include "words-counter.labels" . | nindent 4 }}
{{- end -}}
