apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "words-counter.fullname" . }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: {{ .Values.image.repository }}:{{ .Chart.AppVersion }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - secretRef:
                    name: app-secrets
                - configMapRef:
                    name: app-configs
          restartPolicy: OnFailure
