apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  awsAccessKeyId: <Your AWS Secret Key ID encode to base64>
  awsSecretAccessKey: <Your AWS Secret Access Key encode to base64>
  mysqlUser: <AWS RDS MySQL Username encode to base64>
  mysqlPassword: <AWS RDS MySQL Password encode to base64>
