{
 "title": "aws-mysql",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Top 5 files with largest amount of lines.",
   "type": "table",
   "description": "Top 5 files table with largest amount of lines.",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select `object_path`, `date`, `amount_of_lines` from `lines` order by 3 desc limit 5;"
    }
   ]
  },
  {
   "title": "Top 5 files with largest amount of words.",
   "type": "table",
   "description": "Top 5 files table with largest amount of words.",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select `object_path`,`date`, `amount_of_words` from  `words` order by 3 desc limit 5;\n"
    }
   ]
  },
  {
   "title": "Amount of files added per week",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT YEAR(`date`) AS Year, WEEK(`date`, 0) AS Week, COUNT(*) AS total FROM `lines` GROUP BY Year, Week;"
    }
   ]
  }
 ]
}